apiVersion: v1
kind: Service
metadata:
  name: cart
  labels:
    io.kompose.service: cart
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: cart