apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: catalogue
  name: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: catalogue
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: catalogue
    spec:
      containers:
        - image: {{ .Values.nexus }}/{{ .Values.catalogue.image }}:{{ .Values.tag }}
          livenessProbe:
            exec:
              command:
                - curl
                - -H
                - 'X-INSTANA-SYNTHETIC: 1'
                - -f
                - http://localhost:8080/health
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 10
          name: catalogue
      imagePullSecrets:
      - name: nexus-cred
      restartPolicy: Always
