apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: catalogue
  name: catalogue
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: catalogue