apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: mysql
    spec:
      containers:
        - image: {{ .Values.nexus }}/{{ .Values.mysql.image }}:{{ .Values.tag }}
          name: mysql
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      imagePullSecrets:
        - name: nexus-cred
      restartPolicy: Always
