apiVersion: v1
kind: Service
metadata:
  name: ratings
  labels:
    io.kompose.service: ratings
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: ratings
