# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJuZXh1czozMDk5OSI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJ0Y3dvd2ExMiIsImVtYWlsIjoiZG9ja2VybGl0ZUBnbWFpbC5jb20iLCJhdXRoIjoiWVdSdGFXNDZkR04zYjNkaE1UST0ifX19
kind: Secret
metadata:
  name: nexus-cred
  namespace: default
type: kubernetes.io/dockerconfigjson
