apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: shipping
  name: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: shipping
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: shipping
    spec:
      containers:
        - image: {{ .Values.nexus }}/{{ .Values.shipping.image }}:{{ .Values.tag }}
          name: shipping
          env:
            - name: DB_HOST
              value: mysql.default.svc.cluster.local
            - name: DB_PORT
              value: "3306"
      imagePullSecrets:
        - name: nexus-cred
      restartPolicy: Always
