apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: web
    spec:
      containers:
        - image: {{ .Values.nexus }}/{{ .Values.web.image }}:{{ .Values.tag }}
          livenessProbe:
            exec:
              command:
                - curl
                - -H
                - 'X-INSTANA-SYNTHETIC: 1'
                - -f
                - http://localhost:8080/
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 10
          name: web
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: nexus-cred
      restartPolicy: Always
