---
- name: Install Docker on Ubuntu 24.04
  hosts: all
  become: true
  tasks:
    - name: update all packages
      apt:
        update_cache: yes
    - name: Add pre-requisite packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common


