apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: dmVyeXNlY3JldA==  # base64 encoded password (e.g., "verysecret")
  MYSQL_USER: bXl1c2Vy                   # base64 encoded username (e.g., "myuser")
  MYSQL_PASSWORD: c2VjcmV0               # base64 encoded user password (e.g., "secret")
  DBNAME: bXlkYXRhYmFzZQ==               # base64 encoded user password (e.g., "mydatabase")