apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql-app
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      containers:
        - name: mysql-container
          image: nexus:30999/test-mysql:0695030c7a9c
          ports:
            - containerPort: 8080
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: MYSQL_HOST
              value: mysql.default.svc.cluster.local
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
      imagePullSecrets:
        - name: nexus-cred