apiVersion: v1
kind: Service
metadata:
  name: mysql-app
  namespace: default
spec:
  selector:
    app: mysql-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
