---
# PVC for dump file
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dump-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: dump-pv