---
# Persistent Volume for dump file
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dump-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/dump