---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # Replace these with your base64 encoded values
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk  # "rootpassword"
  MYSQL_DATABASE: bXlkYXRhYmFzZQ==        # "mydatabase"