apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-server2
provisioner: nfs.csi.k8s.io
parameters:
  server: 172.16.0.8
  share: /mnt/dump
  subDir: "file"
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-csi-server2
