apiVersion: v1
kind: Pod
metadata:
  name: nfs-test-pod
spec:
  initContainers:
    - name: init-container
      image: bitnami/mysql:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "mypassword"
      volumeMounts:
        - name: nfs-volume
          mountPath: /bitnami/mysql/data
  containers:
    - name: mysql
      image: bitnami/mysql:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "mypassword"

      volumeMounts:
        - name: nfs-volume
          mountPath: /bitnami/mysql/data
  volumes:
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: nfs-pvc
    - name: dump
      hostPath:
        path: /mnt/dump
        type: Directory

