apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod
spec:
  initContainers:
    - name: test-container
      image: mysql:latest
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: "mypassword"
      volumeMounts:
      - name: nfs-volume
        mountPath: /var/lib/mysql
  containers:
    - name: dump-db
      image: mysql:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "mypassword"
      command: ["/bin/bash"]
      args:
        - "-c"
        - |
          mysql -u root -p$MYSQL_ROOT_PASSWORD  < foo/10-dump.sql
          wait
      volumeMounts:
        - name: nfs-volume
          mountPath: /var/lib/mysql
        - name: dump
          mountPath: /foo
  volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: nfs-pvc
      - name: dump
        persistentVolumeClaim:
           claimName: nfs-pvc-2

