apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-dump-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.16.0.8
    path: /mnt/nfs_share/dump
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-dump-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: nfs-dump-pv