apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=  # base64 encoded password (e.g., "password")
  MYSQL_DATABASE: Y2l0aWVzCg==       # base64 encoded password (e.g., "cities")
  MYSQL_USER: c2hpcHBpbmc=           # base64 encoded username (e.g., "shipping")
  MYSQL_PASSWORD: c2VjcmV0           # base64 encoded user password (e.g., "secret")