---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-2
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-csi-server2