apiVersion: v1
kind: Pod
metadata:
  name: nfs-test-pod
spec:
  containers:
    - name: test-container
      image: mysql:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "mypassword"
      volumeMounts:
        - name: nfs-volume
          mountPath: /var/lib/mysql
        - mountPath:  /foo
          name: dump
          readOnly: false
  volumes:
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: nfs-pvc
    - name: dump
      persistentVolumeClaim:
        claimName: nfs-pvc-2

